"""A broker account per node, and the access list that pens each one in.

One shared account is what makes a stolen node worth stealing: it holds the
server's own credentials, so it can publish anything the server can -- another
node's spawn included. Signing already stops a forged command being acted on;
this stops it being sent, and stops a node reading or disrupting what belongs to
another.

Each node gets its own account, named after the node. The password is derived
from the same secret the signing keys come from, under a context of its own, so
nothing new is stored and a leaked password file says nothing about a signing
key. ``/deploy`` writes the password into the node's ``.env``, the channel that
is authenticated before any of this exists.

The access list is generated for the brokers Wactorz provides (compose, and the
add-on's embedded broker). It is deliberately not an allow-list: agent code picks
its own topics -- the prompts teach `sensors/`, `custom/` and `homeassistant/`,
and a house may carry `zigbee2mqtt/` or anything else -- so naming what is allowed
would break agents that do nothing wrong. Instead every account keeps the broker's
open commons, and each node is denied what is not its own:

- another node's ``nodes/<other>/#`` -- its control topics and its reports, in
  both directions, so a node can neither drive nor impersonate nor watch another;
- ``agents/+/commands``, which stops server-side agents (a node's own agents are
  stopped through its own ``nodes/<node>/stop``);
- ``system/#``, which no node publishes.

Two mosquitto rules make this work, both checked against a real broker in
``tests/`` and in the notes on the plan: a ``deny`` beats every allow whatever
order the file is in, and an account the file does not mention has no access at
all -- which is why the list opens with one pattern granting every account the
commons, including the server's own and any the user added for something else.
"""

from __future__ import annotations

import base64
import hashlib
import os
import re
from collections.abc import Iterable
from pathlib import Path

from .node_signing import derive

#: The generated files, beside the certificates a broker of ours also reads.
PASSWORD_FILE = "node_passwd"  # noqa: S105  # a file name, not a password
ACL_FILE = "acl"

#: Prefixed to a node's name when its password, and that password's salt, are
#: derived. Separate from the signing key's context on purpose: see `derive`.
_PASSWORD_CONTEXT = b"wactorz-node-broker-v1:"
_SALT_CONTEXT = b"wactorz-node-broker-salt-v1:"

#: How mosquitto stores a password: PBKDF2-SHA512, the iteration count in the line.
#: Its own default, low because these passwords are generated and long.
_HASH_ITERATIONS = 101
_HASH_LENGTH = 64
_SALT_LENGTH = 12

#: Denied to every node account, whatever other nodes exist.
FIXED_DENIES = ("agents/+/commands", "system/#")

#: What a node's name may not contain. `+` and `#` are MQTT wildcards and are
#: refused in a username by mosquitto itself; `/` separates topic levels; `:`
#: separates the fields of a password file line, and whitespace ends them.
_FORBIDDEN = re.compile(r"[+#:/\s]")

_HEADER = (
    "# Generated by Wactorz from its node list -- do not edit.\n"
    "# It is written again whenever the nodes change.\n"
)


def name_error(node: str) -> str | None:
    """Why ``node`` cannot name a broker account, or None if it can.

    Loud rather than skipped: a node whose name cannot be an account would
    otherwise be deployed with credentials no broker has, and fail to connect
    with nothing saying why.
    """
    if not node or node.strip() != node:
        return f"Node name {node!r} is empty or padded with whitespace."
    bad = sorted(set(_FORBIDDEN.findall(node)))
    if bad:
        return (
            f"Node name {node!r} contains {' and '.join(repr(c) for c in bad)}, which cannot "
            "appear in a broker account name. Rename the node and deploy it again."
        )
    return None


def password(node: str) -> str:
    """The broker password ``node`` is given, derived rather than stored."""
    raw = derive(_PASSWORD_CONTEXT, node)
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def password_line(node: str) -> str:
    """One mosquitto password-file line for ``node``.

    The salt is derived as well, so the same nodes always produce the same file:
    a broker watching it for changes reloads when the node list changes, and not
    every time the file is written again.
    """
    salt = derive(_SALT_CONTEXT, node)[:_SALT_LENGTH]
    hashed = hashlib.pbkdf2_hmac(
        "sha512", password(node).encode("ascii"), salt, _HASH_ITERATIONS, dklen=_HASH_LENGTH
    )
    return (
        f"{node}:$7${_HASH_ITERATIONS}${base64.b64encode(salt).decode('ascii')}"
        f"${base64.b64encode(hashed).decode('ascii')}"
    )


def password_file_text(nodes: Iterable[str]) -> str:
    """The password file for ``nodes``, for a broker to read beside its own accounts."""
    return "".join(f"{password_line(node)}\n" for node in _checked(nodes))


def acl_text(nodes: Iterable[str]) -> str:
    """The access list: the commons for everyone, and each node denied the others'."""
    names = _checked(nodes)
    blocks = [
        _HEADER,
        "\n# Every account, including ones this file does not name: the server's own,\n"
        "# Home Assistant's, and anything else on this broker.\n"
        "pattern readwrite #\n",
    ]
    for node in names:
        denied = [f"nodes/{other}/#" for other in names if other != node]
        denied.extend(FIXED_DENIES)
        lines = "".join(f"topic deny {topic}\n" for topic in denied)
        blocks.append(f"\nuser {node}\n{lines}")
    return "".join(blocks)


def write_files(directory: Path, nodes: Iterable[str]) -> bool:
    """Write both files for ``nodes``; True when either changed.

    The answer is what tells a broker to read them again, so it is the file's
    content that decides it, not the fact that they were written.
    """
    names = _checked(nodes)
    directory.mkdir(parents=True, exist_ok=True)
    written = [
        _write_private(directory / PASSWORD_FILE, password_file_text(names)),
        _write_private(directory / ACL_FILE, acl_text(names)),
    ]
    return any(written)


def _checked(nodes: Iterable[str]) -> list[str]:
    """The node names, sorted, refusing any that cannot be an account."""
    names = sorted(set(nodes))
    for node in names:
        problem = name_error(node)
        if problem:
            raise ValueError(problem)
    return names


def _write_private(path: Path, text: str) -> bool:
    """Write ``text`` readable by its owner only, and say whether it changed.

    Mosquitto refuses a password file others can read, and warns about an access
    list; these hold what a node authenticates with, so both are 0600.
    """
    data = text.encode("utf-8")
    try:
        if path.read_bytes() == data:
            return False
    except OSError:
        pass
    staging = path.with_name(f".{path.name}.tmp")
    staging.unlink(missing_ok=True)
    fd = os.open(staging, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    with os.fdopen(fd, "wb") as handle:
        handle.write(data)
    staging.replace(path)
    return True
