"""A broker account per node, and the access list that pens each one in.

One shared account is what makes a stolen node worth stealing: it holds the
server's own credentials, so it can publish anything the server can -- another
node's spawn included. Signing already stops a forged command being acted on;
this stops it being sent, and stops a node reading or disrupting what belongs to
another.

Each node gets its own account, named after the node. The password is derived
from the same secret the signing keys come from, under a context of its own, so
nothing new is stored and a leaked password file says nothing about a signing
key. ``/deploy`` writes the password into the node's ``.env``, the channel that
is authenticated before any of this exists.

The access list is generated for the brokers Wactorz provides (compose, and the
add-on's embedded broker), and it is an allow-list. A node account may use:

- its own ``nodes/<name>/#`` -- its control topics and its reports. Another node's
  tree is simply not named, so a node can neither drive nor impersonate nor
  watch another;
- ``agents/#``, the traffic every host's agents share -- status, logs, chat,
  manifests, tasks by name and their replies -- except ``agents/+/commands``,
  which stops server-side agents (a node's own are stopped through its own
  ``nodes/<name>/stop``);
- ``main/llm_request`` and ``main/reply/#``, to write only: it asks main's model
  and answers the tasks main sends, and reads neither, so it cannot watch what
  other nodes answer or learn a reply topic to forge into;
- the data topics agents use by convention (`NODE_TOPICS`), and whatever
  ``WACTORZ_NODE_TOPICS`` adds. Agent code picks its own topics, so one outside
  these is refused by the broker, silently, until its prefix is added: that is
  the price of a stolen node not reaching ``zigbee2mqtt/`` or anything else that
  shares the broker.

The accounts with the whole broker are named too: the server's own, and those
``WACTORZ_BROKER_ACCOUNTS`` lists (Home Assistant's, zigbee2mqtt's). Mosquitto
gives an account the file does not mention no access at all, which is what makes
this an allow-list and also why those have to be listed.

With no nodes there is nobody to pen in, and the list is the open commons: every
account keeps everything, so an install without nodes is not asked to list its
other accounts.

A ``deny`` beats every allow whatever order the file is in; that, and the rest of
how mosquitto reads this file, is checked against a real broker in
``tests/broker``.
"""

import base64
import hashlib
import os
import re
from collections.abc import Iterable
from pathlib import Path

from .node_signing import derive

#: The generated files, beside the certificates a broker of ours also reads.
PASSWORD_FILE = "node_passwd"  # noqa: S105  # a file name, not a password
ACL_FILE = "acl"

#: Prefixed to a node's name when its password, and that password's salt, are
#: derived. Separate from the signing key's context on purpose: see `derive`.
_PASSWORD_CONTEXT = b"wactorz-node-broker-v1:"
_SALT_CONTEXT = b"wactorz-node-broker-salt-v1:"

#: How mosquitto stores a password: PBKDF2-SHA512, the iteration count in the line.
#: Its own default, low because these passwords are generated and long.
_HASH_ITERATIONS = 101
_HASH_LENGTH = 64
_SALT_LENGTH = 12

#: How mosquitto-go-auth stores a password, which is what the official Mosquitto
#: add-on runs. Its defaults, read from its source: PBKDF2-SHA512, the iteration
#: count and key length carried in the line. Its `logins:` option takes one of
#: these with `password_pre_hashed: true`.
_GO_AUTH_ITERATIONS = 100000
_GO_AUTH_SALT_LENGTH = 16
_GO_AUTH_KEY_LENGTH = 32

#: The data topics a node's agents may use without anything being configured:
#: the prefixes the prompts teach and the catalogue agents publish under, and
#: Home Assistant's state changes to read. `WACTORZ_NODE_TOPICS` adds to these.
NODE_TOPICS: tuple[tuple[str, str], ...] = (
    ("custom/#", "readwrite"),
    ("sensors/#", "readwrite"),
    ("home/#", "readwrite"),
    ("schedule/#", "readwrite"),
    ("homeassistant/state_changes/#", "read"),
)

#: Where a configured data topic may not start: these are the fences themselves,
#: and a filter under one of them would take a fence down for every node.
_FENCED = ("nodes/", "agents/", "main/", "system/", "$")

#: What a topic filter in a setting may not contain: it is written into the
#: access list as it is, one rule per line.
_UNSAFE_IN_TOPIC = re.compile(r"[\s\x00]")

#: What a node's name may not contain. `+` and `#` are MQTT wildcards and are
#: refused in a username by mosquitto itself; `/` separates topic levels; `:`
#: separates the fields of a password file line, and whitespace ends them.
_FORBIDDEN = re.compile(r"[+#:/\s]")

_HEADER = (
    "# Generated by Wactorz from its node list -- do not edit.\n"
    "# It is written again whenever the nodes change.\n"
)

#: The list when there is no node: every account, named or not, keeps the whole
#: broker. `pattern`, not `topic`: a `topic` line outside a `user` block reaches
#: anonymous clients only. Mosquitto warns that the pattern names no client,
#: which is expected. $SYS is not covered by an ordinary rule.
_OPEN_COMMONS = (
    "\n# No node is deployed, so there is nobody to pen in: every account keeps the\n"
    "# whole broker.\n"
    "pattern readwrite #\n"
    "pattern read $SYS/#\n"
)


def name_error(node: str) -> str | None:
    """Why ``node`` cannot name a broker account, or None if it can.

    Loud rather than skipped: a node whose name cannot be an account would
    otherwise be deployed with credentials no broker has, and fail to connect
    with nothing saying why.
    """
    if not node or node.strip() != node:
        return f"Node name {node!r} is empty or padded with whitespace."
    bad = sorted(set(_FORBIDDEN.findall(node)))
    if bad:
        return (
            f"Node name {node!r} contains {' and '.join(repr(c) for c in bad)}, which cannot "
            "appear in a broker account name. Rename the node and deploy it again."
        )
    return None


def password(node: str) -> str:
    """The broker password ``node`` is given, derived rather than stored."""
    raw = derive(_PASSWORD_CONTEXT, node)
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def password_line(node: str) -> str:
    """One mosquitto password-file line for ``node``.

    The salt is derived as well, so the same nodes always produce the same file:
    a broker watching it for changes reloads when the node list changes, and not
    every time the file is written again.
    """
    salt = derive(_SALT_CONTEXT, node)[:_SALT_LENGTH]
    hashed = hashlib.pbkdf2_hmac(
        "sha512", password(node).encode("ascii"), salt, _HASH_ITERATIONS, dklen=_HASH_LENGTH
    )
    return (
        f"{node}:$7${_HASH_ITERATIONS}${base64.b64encode(salt).decode('ascii')}"
        f"${base64.b64encode(hashed).decode('ascii')}"
    )


def password_file_text(nodes: Iterable[str]) -> str:
    """The password file for ``nodes``, for a broker to read beside its own accounts."""
    return "".join(f"{password_line(node)}\n" for node in _checked(nodes))


def parse_node_topics(raw: str) -> list[tuple[str, str]]:
    """The data topics a setting adds for nodes, as (filter, access) pairs.

    Comma-separated topic filters; one prefixed ``read:`` may be read and not
    written. Raises ``ValueError`` for one that could not be a rule, or that
    would open one of the fences the list exists to keep.
    """
    topics: list[tuple[str, str]] = []
    for part in raw.split(","):
        entry = part.strip()
        if not entry:
            continue
        access = "readwrite"
        if entry.startswith("read:"):
            access, entry = "read", entry[len("read:") :].strip()
        problem = _topic_error(entry)
        if problem:
            raise ValueError(problem)
        topics.append((entry, access))
    return topics


def parse_accounts(raw: str) -> list[str]:
    """The account names a setting lists, comma-separated."""
    return [name.strip() for name in raw.split(",") if name.strip()]


def _topic_error(topic: str) -> str | None:
    """Why ``topic`` cannot be a data topic for nodes, or None if it can."""
    if not topic or _UNSAFE_IN_TOPIC.search(topic):
        return f"Topic filter {topic!r} is empty or contains whitespace."
    if "#" in topic[:-1] or (topic.endswith("#") and topic != "#" and not topic.endswith("/#")):
        return f"Topic filter {topic!r} uses '#' somewhere other than as its last level."
    if topic == "#" or topic.startswith(_FENCED):
        return (
            f"Topic filter {topic!r} would give every node what the access list keeps from "
            "it: a data topic may not be '#', nor start with nodes/, agents/, main/, system/ or $."
        )
    return None


def acl_text(
    nodes: Iterable[str],
    full_access: Iterable[str] = (),
    node_topics: Iterable[tuple[str, str]] = NODE_TOPICS,
) -> str:
    """The access list: what each node may use, and the accounts with the whole broker.

    ``full_access`` names the server's own account and any other that shares the
    broker; ``node_topics`` is what every node's agents may use for data.
    """
    names = _checked(nodes)
    if not names:
        return _HEADER + _OPEN_COMMONS
    trusted = [account for account in _checked(full_access) if account not in names]
    blocks = [_HEADER]
    if trusted:
        blocks.append(
            "\n# The accounts with the whole broker: the server's own, and those listed in\n"
            "# WACTORZ_BROKER_ACCOUNTS. An account this file does not name has no access.\n"
            "# $SYS is the broker's own statistics, which no ordinary rule covers and the\n"
            "# compose broker's health check reads.\n"
        )
        blocks.extend(
            f"user {account}\ntopic readwrite #\ntopic read $SYS/#\n" for account in trusted
        )
    else:
        blocks.append(
            "\n# The server connects with no account, so the whole broker goes to clients\n"
            "# that give none: a `topic` line outside a `user` block reaches only those.\n"
            "topic readwrite #\ntopic read $SYS/#\n"
        )
    data = "".join(f"topic {access} {topic}\n" for topic, access in node_topics)
    for node in names:
        blocks.append(
            f"\nuser {node}\n"
            "# Its own control topics and reports.\n"
            f"topic readwrite nodes/{node}/#\n"
            "# What every host's agents share, except the commands that stop the server's.\n"
            "topic readwrite agents/#\n"
            "topic deny agents/+/commands\n"
            "# Asking main's model and answering main's tasks: written, never read.\n"
            "topic write main/llm_request\n"
            "topic write main/reply/#\n"
            "# Data its agents publish and read.\n"
            f"{data}"
        )
    return "".join(blocks)


def home_assistant_login(node: str) -> str:
    """``node``'s password, hashed the way the official Mosquitto add-on stores one."""
    salt = derive(_SALT_CONTEXT, node)[:_GO_AUTH_SALT_LENGTH]
    hashed = hashlib.pbkdf2_hmac(
        "sha512",
        password(node).encode("ascii"),
        salt,
        _GO_AUTH_ITERATIONS,
        dklen=_GO_AUTH_KEY_LENGTH,
    )
    return (
        f"PBKDF2$sha512${_GO_AUTH_ITERATIONS}${base64.b64encode(salt).decode('ascii')}"
        f"${base64.b64encode(hashed).decode('ascii')}"
    )


def home_assistant_logins(nodes: Iterable[str]) -> str:
    """The `logins:` block for the official Mosquitto add-on, to paste into its options.

    Written out rather than applied: that add-on keeps its own accounts, and no
    add-on may edit another's configuration. Its access lists cannot be enforced
    from outside either -- its authentication plugin answers first -- so this is
    accounts alone: a stolen node's credentials can be revoked, but the broker will
    not keep one node out of another's topics.
    """
    lines = [
        "# Generated by Wactorz from its deploy targets -- paste into the Mosquitto\n",
        "# add-on's configuration, keeping any logins already there.\n",
        "logins:\n",
    ]
    for node in _checked(nodes):
        lines.append(
            f"  - username: {node}\n"
            f'    password: "{home_assistant_login(node)}"\n'
            f"    password_pre_hashed: true\n"
        )
    return "".join(lines)


def write_files(
    directory: Path,
    nodes: Iterable[str],
    full_access: Iterable[str] = (),
    node_topics: Iterable[tuple[str, str]] = NODE_TOPICS,
) -> bool:
    """Write both files for ``nodes``; True when either changed.

    The answer is what tells a broker to read them again, so it is the file's
    content that decides it, not the fact that they were written.
    """
    names = _checked(nodes)
    acl = acl_text(names, full_access, node_topics)
    directory.mkdir(parents=True, exist_ok=True)
    written = [
        _write_private(directory / PASSWORD_FILE, password_file_text(names)),
        _write_private(directory / ACL_FILE, acl),
    ]
    return any(written)


def _checked(nodes: Iterable[str]) -> list[str]:
    """The node names, sorted, refusing any that cannot be an account."""
    names = sorted(set(nodes))
    for node in names:
        problem = name_error(node)
        if problem:
            raise ValueError(problem)
    return names


def _write_private(path: Path, text: str) -> bool:
    """Write ``text`` readable by its owner only, and say whether it changed.

    Mosquitto refuses a password file others can read, and warns about an access
    list; these hold what a node authenticates with, so both are 0600.
    """
    data = text.encode("utf-8")
    try:
        if path.read_bytes() == data:
            return False
    except OSError:
        pass
    staging = path.with_name(f".{path.name}.tmp")
    staging.unlink(missing_ok=True)
    fd = os.open(staging, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    with os.fdopen(fd, "wb") as handle:
        handle.write(data)
    staging.replace(path)
    return True
