"""The unified persist()/recall() API agents actually call.

Routes each key to the store that suits it, so agent code needs no knowledge of
which backend holds what.
"""

import logging
from typing import Any

from .db import WactorzDB
from .pickle_store import PickleStore
from .stores import get_memory_store

logger = logging.getLogger(__name__)

# ── Unified Persistence API ───────────────────────────────────────────────
# This is the compatibility shim. It replaces the raw pickle persist/recall
# on Actor with intelligent routing based on key names.

# Keys that go to SQLite (durable, structured, queryable)
SQLITE_KEYS = {
    "_spawned_agents",
    "_pipeline_rules",
    "_user_facts",
    "_notification_urls",
    "_topic_contracts",
    "_agent_manifests",
    "conversation_history",  # must survive restarts — durable
    "history_summary",  # must survive restarts — durable
    "_final_cost",  # lifetime LLM cost — durable, queryable for deleted agents
    "_messages_processed",  # lifetime message count — durable, survives restarts
}

# High-frequency values kept in process memory. Each is regenerated by normal
# operation, so they are safe to lose on restart.
EPHEMERAL_KEYS = {
    "_observed_samples",  # rebuilt on first publish anyway
    "_agent_metrics",  # rebuilt from heartbeats
    "_heartbeat_state",  # rebuilt on agent start
}


class PersistenceAPI:
    """Drop-in replacement for Actor.persist() / Actor.recall().

    Routes data to the correct store based on key name:
      - Known structured keys → SQLite
      - Known ephemeral keys → process memory
      - Everything else → Pickle (agent.state, models, etc.)

    Usage in Actor.__init__:
        self._persistence = PersistenceAPI(db, pickle_store, self.name)

    Then persist/recall delegate:
        def persist(self, key, value):
            self._persistence.set(key, value)

        def recall(self, key, default=None):
            return self._persistence.get(key, default)
    """

    def __init__(self, db: WactorzDB, pickle_store: PickleStore, agent_name: str) -> None:
        self.db = db
        self.memory = get_memory_store()
        self.pickle = pickle_store
        self.agent = agent_name

    def set(self, key: str, value: Any) -> None:
        """Set a key-value pair in the related store."""
        if key in SQLITE_KEYS:
            self.db.kv_set(self.agent, key, value)
        elif key in EPHEMERAL_KEYS:
            self.memory.set(f"{self.agent}:{key}", value)
        else:
            # Arbitrary Python object → pickle
            state = self.pickle.load(self.agent)
            state[key] = value
            self.pickle.save(self.agent, state)

    def get(self, key: str, default: Any = None) -> Any:
        """Get a value from the relevant store."""
        if key in SQLITE_KEYS:
            return self.db.kv_get(self.agent, key, default)
        if key in EPHEMERAL_KEYS:
            return self.memory.get(f"{self.agent}:{key}", default)
        state = self.pickle.load(self.agent)
        return state.get(key, default)

    def delete(self, key: str) -> None:
        """Delete a key-value pair from the related store."""
        if key in SQLITE_KEYS:
            self.db.kv_delete(self.agent, key)
        elif key in EPHEMERAL_KEYS:
            self.memory.delete(f"{self.agent}:{key}")
        else:
            state = self.pickle.load(self.agent)
            state.pop(key, None)
            self.pickle.save(self.agent, state)

    def all(self) -> dict[str, Any]:
        """Return all key-value pairs across all stores."""
        result = {}
        result.update(self.db.kv_all(self.agent))
        for key in EPHEMERAL_KEYS:
            val = self.memory.get(f"{self.agent}:{key}")
            if val is not None:
                result[key] = val
        result.update(self.pickle.load(self.agent))
        return result

    def load_snapshot(self, snapshot: dict[str, Any], *, replace: bool = True) -> dict[str, Any]:
        """Bulk-load a state snapshot (the inverse of all()).

        Used at migration time: the source node ships its complete state, and
        the destination calls this once BEFORE the agent's on_start() runs so
        recall() finds the migrated values during initialization.

        When ``replace`` is True (default), every existing value for this
        agent is wiped first — this is the correct semantics for migration,
        where the incoming snapshot must fully replace any stale local state
        from a prior incarnation of the same name. Pass replace=False for
        merge semantics (advanced; rarely the right thing).

        Returns a summary dict for logging.
        """
        if replace:
            self.purge()

        applied = {"sqlite": 0, "memory": 0, "pickle": 0}
        if not isinstance(snapshot, dict):
            return applied

        # Pickle keys are anything not in the SQLite or ephemeral sets — we group
        # them so one disk write covers all of them instead of N writes.
        pickle_blob: dict = {}
        for key, value in snapshot.items():
            try:
                if key in SQLITE_KEYS:
                    self.db.kv_set(self.agent, key, value)
                    applied["sqlite"] += 1
                elif key in EPHEMERAL_KEYS:
                    self.memory.set(f"{self.agent}:{key}", value)
                    applied["memory"] += 1
                else:
                    pickle_blob[key] = value
            except Exception as e:
                logger.warning(
                    "[Persistence] Could not load snapshot key '%s' for '%s': %s",
                    key,
                    self.agent,
                    e,
                )

        if pickle_blob:
            try:
                self.pickle.save(self.agent, pickle_blob)
                applied["pickle"] = len(pickle_blob)
            except Exception as e:
                logger.warning("[Persistence] Pickle bulk-load failed for '%s': %s", self.agent, e)

        logger.info(
            "[Persistence] Loaded snapshot for '%s': %s SQLite keys, %s in-memory keys, %s pickle keys",
            self.agent,
            applied["sqlite"],
            applied["memory"],
            applied["pickle"],
        )
        return applied

    def purge(self) -> dict[str, Any]:
        """Permanently delete EVERY stored value for this agent across all
        backends (SQLite kv_store, in-memory ephemeral keys, pickle state file).

        Use this only when the agent is being fully deleted — not on stop or
        restart. Returns a small summary dict, useful for logging:

            {"sqlite_rows": int, "memory_keys": int, "pickle_deleted": bool}
        """
        summary = {"sqlite_rows": 0, "memory_keys": 0, "pickle_deleted": False}

        # 1. SQLite — drop every row this agent owns in kv_store.
        try:
            summary["sqlite_rows"] = self.db.kv_purge_agent(self.agent)
        except Exception as e:
            logger.warning("[Persistence] SQLite purge failed for %s: %s", self.agent, e)

        # 2. Process memory — only the known ephemeral keys live there.
        for key in EPHEMERAL_KEYS:
            try:
                self.memory.delete(f"{self.agent}:{key}")
                summary["memory_keys"] += 1
            except Exception as e:
                logger.debug("[Persistence] memory delete %s failed: %s", key, e)

        # 3. Pickle — remove the agent's state.pkl on disk.
        try:
            self.pickle.delete(self.agent)
            summary["pickle_deleted"] = True
        except Exception as e:
            logger.warning("[Persistence] Pickle delete failed for %s: %s", self.agent, e)

        logger.info(
            "[Persistence] Purged agent '%s': %s SQLite rows, %s in-memory keys, pickle_deleted=%s",
            self.agent,
            summary["sqlite_rows"],
            summary["memory_keys"],
            summary["pickle_deleted"],
        )
        return summary
