name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - name: Install Python dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[all,dev]"

      - name: Python tests
        run: make test-py

      - name: Python coverage
        run: make coverage-py

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            coverage/python-coverage.xml
